# Generated by Django 5.0.6 on 2024-05-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='text3',
            field=models.TextField(blank=True, verbose_name='Text'),
        ),
    ]
