# Generated by Django 5.0.6 on 2024-05-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_background_text3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='background',
            name='text3',
        ),
    ]
