# Generated by Django 5.0.6 on 2024-05-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_background_text2_remove_background_text3'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='text2',
            field=models.TextField(blank=True, verbose_name='Text2'),
        ),
        migrations.AddField(
            model_name='background',
            name='text3',
            field=models.TextField(blank=True, verbose_name='Text3'),
        ),
    ]
