# Generated by Django 5.0.6 on 2024-05-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Image of boat'),
        ),
    ]
