# Generated by Django 5.0.6 on 2024-05-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_about_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='boat', verbose_name='Image')),
                ('text1', models.TextField(verbose_name='Text')),
                ('button', models.CharField(max_length=10, verbose_name='Button')),
            ],
        ),
    ]
