# Generated by Django 5.0.6 on 2024-05-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review1', models.TextField(verbose_name='Text')),
                ('review2', models.TextField(verbose_name='Text2')),
                ('review3', models.TextField(verbose_name='Text3')),
                ('review4', models.TextField(verbose_name='Text4')),
            ],
        ),
    ]
